name: portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ícones iOS
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.6

  # GraphQL para API do Autentique
  graphql_flutter: ^5.2.0-beta.6

  # HTTP + upload
  dio: ^5.1.2
  file_picker: ^10.1.7

  # carregar variáveis de ambiente (.env)
  flutter_dotenv: ^5.1.1

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

dependency_overrides:
  firebase_core_platform_interface: 5.0.0
  firebase_auth_platform_interface: 7.0.0