name: portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  graphql_flutter: ^5.2.0-beta.6
  gql_dio_link: ^1.0.1+1
  dio: ^5.1.2
  file_picker: ^8.0.7
  flutter_dotenv: ^5.1.1
  firebase_core: 2.30.0
  firebase_auth: 4.15.3
  cloud_firestore: ^4.16.5
  mime: ^1.0.5
  mask_text_input_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0 
  url_launcher: ^6.2.6
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env